### ISSUE TITLE
Error in image_to_color.py while using as library: Line 36

### ISSUE THREAD

**Issue by newpokemon** [algolia/color-extractor#9]
Hey Thank for the fabulous work!

I tried and CLI is working perfectly fine. However, when tried as library in a python file, giving this error:

Traceback (most recent call last):
  File "test.py", line 10, in <module>
    print(img_to_color.get(img))
  File "/home/color-extractor-master/color_extractor/image_to_color.py", line 36, in get
    if self._settings['debug'] is None:
KeyError: 'debug'

Non CS background so might overlook something, please help!
Thanks in advance.

**Comment by gauthamk28** [comment]
I am also getting the same error , someone please help to fix this error
Thanks in advance

**Comment by aliabdullah176** [comment]
Same error, any idea whats going wrong?

**Comment by samantharachelb** [comment]
try passing the debug setting as a dictionary

to get all the info:
```python
settings = {'debug': {}}

image_to_color = ImageToColor(npz['samples'], npz['labels'], settings)
```

to get just the color name:
```python
settings = { 'debug': None }

image_to_color = ImageToColor(npz['samples'], npz['labels'], settings)
```

**Comment by Davi-jeon** [comment]
I' have also same issuse. so, I've tried CLI on jupyter noteobok as below.

`import os
import pandas as pd

files= os.listdir("./imgs")

img_name= []
colors= []

for i in files:
    order= "./color-extractor color_names.npz ./imgs/"+i
    result= !{order}
    
    img_name.append(i)
    colors.append(result)

df= pd.DataFrame({"img_name":img_name, "colors": colors})`

**Comment by Anishauday** [comment]
![Screenshot 2021-01-22 125421](https://user-images.githubusercontent.com/74710792/105459996-271b4f00-5cb1-11eb-885e-75db258617da.png)
I'm getting the above error. Can anyone help how extract the color details?
